site_name: Corewar.io Documentation
repo_url: https://github.com/gareththegeek/corewar
pages:
- Home: index.md
- Guide to Corewar: corewar/index.md
- Redcode Reference:
   - Intro: redcode/index.md
   - Operands: redcode/operands.md
   - Opcodes: redcode/opcodes.md
   - Modifiers: redcode/modifiers.md
   - Addressing Modes: redcode/addressing_modes.md
   - Parser: redcode/parser.md
- Developer Reference: developer/index.md
theme: readthedocs