site_name: Corewar.io Documentation
repo_url: https://github.com/gareththegeek/corewar
pages:
- Home: index.md
- Guide to Corewar: corewar/index.md
  #- Sub pages go here: 
- Redcode Reference: redcode/index.md
- Developer Reference: developer/index.md
theme: readthedocs