site_name: Corewar.io Documentation
repo_url: https://github.com/gareththegeek/corewar
pages:
- Home: 'index.md'
- Guide to Corewar: 'corewar/index.md'
- Redcode Reference: 'redcode/index.md'
  - Opcodes: 'redcode/opcodes.md'
  - Modifiers: 'redcode/modifiers.md'
  - Addressing Modes: 'redcode/addressing_modes.md'
- Developer Reference: 'developer/index.md'
theme: readthedocs